services:
  frontend:
    image: isvvc22/frontend-devops:latest
    container_name: frontend_container
    ports:
      - "3000:80"
    depends_on:
      - backend_despacho
      - backend_ventas
    restart: always

  backend_despacho:
    image: isvvc22/backend-despacho-devops:latest
    container_name: backend_despacho_container
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/appdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    restart: always

  backend_ventas:
    image: isvvc22/backend-ventas-devops:latest
    container_name: backend_ventas_container
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/appdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: